# TensorFlow Basics
Understanding the basic functions of tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

1.11.0


### Sessions

In [20]:
tensor_1 = tf.constant(1)
tensor_2 = tf.constant(2)

print(tensor_1)
print(tensor_2)

tensor_1 + tensor_2 #Have to run in a session 

Tensor("Const_4:0", shape=(), dtype=int32)
Tensor("Const_5:0", shape=(), dtype=int32)


<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [13]:
with tf.Session() as sess:
    result = sess.run(tensor_1+tensor_2)
    sess.close()
    
    
print(result)

3


In [28]:
with tf.Session() as sess:
    
    myrandn = tf.random_normal((4,4),mean=0,stddev=0.5)
    print(myrandn)
    print(myrandn.eval())
    print(sess.run(myrandn))
    print()
    
    
    #Matrix multiplication
    X = tf.constant([[10],[100],[1],[-5]],dtype=tf.float32)
    result = tf.matmul(myrandn,X)
    print(result.eval())
    
    
    sess.close()

Tensor("random_normal_13:0", shape=(4, 4), dtype=float32)
[[ 1.0019026   0.658679    0.90062153  0.1944328 ]
 [-0.44954526 -0.4832348   0.2292727   0.52151644]
 [-0.04629505 -0.45660898 -0.22665861 -0.7832231 ]
 [ 0.33954495 -0.13999565 -0.05296539 -0.24193694]]
[[ 0.4468496   0.6572182  -0.1324695   0.21646376]
 [ 0.30305642  0.5095135   0.01301672  0.10474817]
 [ 0.40477908  0.55571723 -0.08683411 -0.24707891]
 [-0.0645182   0.4177263  -0.09684841 -0.74011105]]

[[  6.4021273]
 [ 38.90714  ]
 [-17.577774 ]
 [ 31.89394  ]]


### Variables and Placeholders

In [37]:
my_tensor = tf.random_uniform((2,2),-1,1)
my_var = tf.Variable(initial_value=my_tensor)
init = tf.global_variables_initializer() #initialize variables 

with tf.Session() as sess:
    init.run()
    
    print(my_var.eval())
    
    ph = tf.placeholder(tf.float64)
    
    print(ph)

[[ 0.6866169  -0.4819522 ]
 [ 0.85360885 -0.17447138]]
Tensor("Placeholder:0", dtype=float64)
